### ISSUE TITLE
FETCH_HEADではなくHEADを参照する

### ISSUE THREAD

**Issue by otofune** [kyoppie/kyoppie-web#29]
更新していないときに必ずこけます (要するに初回構築時)
fetchだけすることもできるので、実際のHEADの参照先を見るべき
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/otofune/kyoppie/web/src/controllers/_/ajax.py", line 24, in get_commit
    f = open("../.git/FETCH_HEAD","r")
FileNotFoundError: [Errno 2] No such file or directory: '../.git/FETCH_HEAD'
```

**Comment by otofune** [comment]
具体的には、 `.git/HEAD` の内容が `ref: (任意のrefs/以下のパス)` ならば指し示されているパスに存在するファイルの内容を取得、そうでなければ (そうでない場合は意図的に `git checkout (任意のコミットSHA-1ハッシュ)` で引き起こせる) HEADの内容を取得することで、コミットSHA-1ハッシュが得られる
もしくは、 `git symbolic-ref HEAD` を実行し応答が `fatal: (任意のエラーメッセージ)` (Ex: `fatal: ref HEAD is not a symbolic ref` ) 以外であれば取得できたパスを読み取り、そうでなければHEADを読み取るというアプローチも取れる

**Comment by Petitsurume** [comment]
スッ・・・(assign)

**Comment by otofune** [comment]
assignされてしまったあなた
