### ISSUE TITLE
README通りにルートディレクトリで実行するとtojinjaが相対パスでjade参照不可

### ISSUE THREAD

**Issue by otofune** [kyoppie/kyoppie-web#31]
```
[2017-02-13 22:18:28,915] ERROR in app: Exception on /_/tojinja/post [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/otofune/kyoppie/web/src/controllers/_/tojinja.py", line 29, in pf
    return tojinja(template_name)
  File "/home/otofune/kyoppie/web/src/controllers/_/tojinja.py", line 10, in tojinja
    open(path,"r",encoding="utf-8").read(),
FileNotFoundError: [Errno 2] No such file or directory: './views/common/post.jade'
```

**Comment by otofune** [comment]
src内で実行すると動く
